name: authentika
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  flutter_tesseract_ocr: ^0.3.4
  image_picker:  ^0.8.7+4
  web3dart: ^2.3.0
  http: ^0.13.6
  firebase_core: ^2.24.2
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.17.5
  firebase_auth_web: 5.12.0
  diacritic: ^0.1.3
  collection: ^1.17.1
  csv: ^5.0.2
  file_picker: ^6.1.1
  excel: ^2.1.0 # ✅ Ajout corrigé ici
  mobile_scanner: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.jpeg
    - assets/images/light-1.png
    - assets/images/light-2.png
    - assets/images/clock.png
